/* unattended-setup-box.c generated by valac 0.26.1, the Vala compiler
 * generated from unattended-setup-box.vala, do not modify */

/* This file is part of GNOME Boxes. License: LGPLv2+*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>


#define BOXES_TYPE_UNATTENDED_SETUP_BOX (boxes_unattended_setup_box_get_type ())
#define BOXES_UNATTENDED_SETUP_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOXES_TYPE_UNATTENDED_SETUP_BOX, BoxesUnattendedSetupBox))
#define BOXES_UNATTENDED_SETUP_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOXES_TYPE_UNATTENDED_SETUP_BOX, BoxesUnattendedSetupBoxClass))
#define BOXES_IS_UNATTENDED_SETUP_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOXES_TYPE_UNATTENDED_SETUP_BOX))
#define BOXES_IS_UNATTENDED_SETUP_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOXES_TYPE_UNATTENDED_SETUP_BOX))
#define BOXES_UNATTENDED_SETUP_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOXES_TYPE_UNATTENDED_SETUP_BOX, BoxesUnattendedSetupBoxClass))

typedef struct _BoxesUnattendedSetupBox BoxesUnattendedSetupBox;
typedef struct _BoxesUnattendedSetupBoxClass BoxesUnattendedSetupBoxClass;
typedef struct _BoxesUnattendedSetupBoxPrivate BoxesUnattendedSetupBoxPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _BoxesUnattendedSetupBox {
	GtkBox parent_instance;
	BoxesUnattendedSetupBoxPrivate * priv;
};

struct _BoxesUnattendedSetupBoxClass {
	GtkBoxClass parent_class;
};

struct _BoxesUnattendedSetupBoxPrivate {
	GtkInfoBar* needs_internet_bar;
	GtkLabel* needs_internet_label;
	GtkGrid* setup_grid;
	GtkLabel* express_label;
	GtkSwitch* express_toggle;
	GtkImage* user_avatar;
	GtkEntry* username_entry;
	GtkNotebook* password_notebook;
	GtkEntry* password_entry;
	GtkLabel* product_key_label;
	GtkEntry* product_key_entry;
	gchar* product_key_format;
	gboolean we_inserted_text;
};


static gpointer boxes_unattended_setup_box_parent_class = NULL;

GType boxes_unattended_setup_box_get_type (void) G_GNUC_CONST;
#define BOXES_UNATTENDED_SETUP_BOX_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BOXES_TYPE_UNATTENDED_SETUP_BOX, BoxesUnattendedSetupBoxPrivate))
enum  {
	BOXES_UNATTENDED_SETUP_BOX_DUMMY_PROPERTY,
	BOXES_UNATTENDED_SETUP_BOX_READY_FOR_EXPRESS,
	BOXES_UNATTENDED_SETUP_BOX_READY_TO_CREATE,
	BOXES_UNATTENDED_SETUP_BOX_EXPRESS_INSTALL,
	BOXES_UNATTENDED_SETUP_BOX_USERNAME,
	BOXES_UNATTENDED_SETUP_BOX_PASSWORD,
	BOXES_UNATTENDED_SETUP_BOX_HIDDEN_PASSWORD,
	BOXES_UNATTENDED_SETUP_BOX_PRODUCT_KEY,
	BOXES_UNATTENDED_SETUP_BOX_AVATAR_PATH
};
BoxesUnattendedSetupBox* boxes_unattended_setup_box_new (gboolean live, const gchar* product_key_format, gboolean needs_internet, const gchar* os_name);
BoxesUnattendedSetupBox* boxes_unattended_setup_box_construct (GType object_type, gboolean live, const gchar* product_key_format, gboolean needs_internet, const gchar* os_name);
static void boxes_unattended_setup_box_setup_express_toggle (BoxesUnattendedSetupBox* self, gboolean live, gboolean needs_internet);
void boxes_unattended_setup_box_clean_up (BoxesUnattendedSetupBox* self);
static void boxes_unattended_setup_box_update_express_toggle (BoxesUnattendedSetupBox* self, gboolean network_available);
static void _boxes_unattended_setup_box_update_express_toggle_g_network_monitor_network_changed (GNetworkMonitor* _sender, gboolean available, gpointer self);
static void boxes_unattended_setup_box_on_mandatory_input_changed (BoxesUnattendedSetupBox* self);
static void _boxes_unattended_setup_box_on_mandatory_input_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void boxes_unattended_setup_box_on_username_entry_activated (BoxesUnattendedSetupBox* self);
gboolean boxes_unattended_setup_box_get_ready_for_express (BoxesUnattendedSetupBox* self);
const gchar* boxes_unattended_setup_box_get_username (BoxesUnattendedSetupBox* self);
static void _boxes_unattended_setup_box_on_username_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self);
static void boxes_unattended_setup_box_on_password_button_clicked (BoxesUnattendedSetupBox* self);
static void _boxes_unattended_setup_box_on_password_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static gboolean boxes_unattended_setup_box_on_password_entry_focus_out (BoxesUnattendedSetupBox* self);
static gboolean _boxes_unattended_setup_box_on_password_entry_focus_out_gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self);
static void boxes_unattended_setup_box_on_password_entry_activated (BoxesUnattendedSetupBox* self);
static void _boxes_unattended_setup_box_on_password_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self);
static void boxes_unattended_setup_box_on_key_entry_activated (BoxesUnattendedSetupBox* self);
static void _boxes_unattended_setup_box_on_key_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self);
static void boxes_unattended_setup_box_on_key_text_inserted (BoxesUnattendedSetupBox* self, const gchar* text, gint text_length, gint* position);
static void _boxes_unattended_setup_box_on_key_text_inserted_gtk_editable_insert_text (GtkEditable* _sender, const gchar* new_text, gint new_text_length, gint* position, gpointer self);
gboolean boxes_unattended_setup_box_get_ready_to_create (BoxesUnattendedSetupBox* self);
gboolean boxes_unattended_setup_box_get_express_install (BoxesUnattendedSetupBox* self);
void boxes_unattended_setup_box_set_express_install (BoxesUnattendedSetupBox* self, gboolean value);
gchar* boxes_unattended_setup_box_get_password (BoxesUnattendedSetupBox* self);
gchar* boxes_unattended_setup_box_get_hidden_password (BoxesUnattendedSetupBox* self);
gchar* boxes_unattended_setup_box_get_product_key (BoxesUnattendedSetupBox* self);
void boxes_unattended_setup_box_set_avatar_path (BoxesUnattendedSetupBox* self, const gchar* value);
static void boxes_unattended_setup_box_finalize (GObject* obj);
static void _vala_boxes_unattended_setup_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_boxes_unattended_setup_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


BoxesUnattendedSetupBox* boxes_unattended_setup_box_construct (GType object_type, gboolean live, const gchar* product_key_format, gboolean needs_internet, const gchar* os_name) {
	BoxesUnattendedSetupBox * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GtkEntry* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	gchar* msg = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	GtkLabel* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	GtkInfoBar* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	const gchar* _tmp13_ = NULL;
	GtkGrid* _tmp24_ = NULL;
	GList* _tmp25_ = NULL;
#line 94 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (os_name != NULL, NULL);
#line 94 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	self = (BoxesUnattendedSetupBox*) g_object_new (object_type, NULL);
#line 95 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = product_key_format;
#line 95 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 95 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_free0 (self->priv->product_key_format);
#line 95 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	self->priv->product_key_format = _tmp1_;
#line 96 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = self->priv->username_entry;
#line 96 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp3_ = g_get_user_name ();
#line 96 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_entry_set_text (_tmp2_, _tmp3_);
#line 98 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp4_ = live;
#line 98 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp5_ = needs_internet;
#line 98 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_setup_express_toggle (self, _tmp4_, _tmp5_);
#line 99 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp6_ = _ ("Express installation of %s requires an internet connection.");
#line 99 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp7_ = os_name;
#line 99 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp8_ = g_strdup_printf (_tmp6_, _tmp7_);
#line 99 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	msg = _tmp8_;
#line 100 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp9_ = self->priv->needs_internet_label;
#line 100 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp10_ = msg;
#line 100 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_label_set_label (_tmp9_, _tmp10_);
#line 101 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp11_ = self->priv->needs_internet_bar;
#line 101 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp12_ = needs_internet;
#line 101 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp11_, _tmp12_);
#line 103 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp13_ = product_key_format;
#line 103 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp13_ != NULL) {
#line 175 "unattended-setup-box.c"
		GtkLabel* _tmp14_ = NULL;
		GtkEntry* _tmp15_ = NULL;
		GtkEntry* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		gint _tmp18_ = 0;
		gint _tmp19_ = 0;
		GtkEntry* _tmp20_ = NULL;
		const gchar* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
#line 104 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp14_ = self->priv->product_key_label;
#line 104 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp14_, TRUE);
#line 106 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp15_ = self->priv->product_key_entry;
#line 106 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp15_, TRUE);
#line 107 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp16_ = self->priv->product_key_entry;
#line 107 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp17_ = product_key_format;
#line 107 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp18_ = strlen (_tmp17_);
#line 107 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp19_ = _tmp18_;
#line 107 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_entry_set_width_chars (_tmp16_, _tmp19_);
#line 108 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp20_ = self->priv->product_key_entry;
#line 108 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp21_ = product_key_format;
#line 108 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp22_ = strlen (_tmp21_);
#line 108 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp23_ = _tmp22_;
#line 108 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_entry_set_max_length (_tmp20_, _tmp23_);
#line 214 "unattended-setup-box.c"
	}
#line 111 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp24_ = self->priv->setup_grid;
#line 111 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp25_ = gtk_container_get_children ((GtkContainer*) _tmp24_);
#line 220 "unattended-setup-box.c"
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
#line 111 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		child_collection = _tmp25_;
#line 111 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
#line 228 "unattended-setup-box.c"
			GtkWidget* child = NULL;
#line 111 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			child = (GtkWidget*) child_it->data;
#line 232 "unattended-setup-box.c"
			{
				gboolean _tmp26_ = FALSE;
				GtkWidget* _tmp27_ = NULL;
				GtkLabel* _tmp28_ = NULL;
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp27_ = child;
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp28_ = self->priv->express_label;
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				if (_tmp27_ != G_TYPE_CHECK_INSTANCE_CAST (_tmp28_, gtk_widget_get_type (), GtkWidget)) {
#line 243 "unattended-setup-box.c"
					GtkWidget* _tmp29_ = NULL;
					GtkSwitch* _tmp30_ = NULL;
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp29_ = child;
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp30_ = self->priv->express_toggle;
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp26_ = _tmp29_ != G_TYPE_CHECK_INSTANCE_CAST (_tmp30_, gtk_widget_get_type (), GtkWidget);
#line 252 "unattended-setup-box.c"
				} else {
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp26_ = FALSE;
#line 256 "unattended-setup-box.c"
				}
#line 112 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				if (_tmp26_) {
#line 260 "unattended-setup-box.c"
					GtkSwitch* _tmp31_ = NULL;
					GtkWidget* _tmp32_ = NULL;
#line 113 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp31_ = self->priv->express_toggle;
#line 113 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp32_ = child;
#line 113 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					g_object_bind_property_with_closures ((GObject*) _tmp31_, "active", (GObject*) _tmp32_, "sensitive", G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 269 "unattended-setup-box.c"
				}
			}
		}
#line 111 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_g_list_free0 (child_collection);
#line 275 "unattended-setup-box.c"
	}
#line 94 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_free0 (msg);
#line 94 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return self;
#line 281 "unattended-setup-box.c"
}


BoxesUnattendedSetupBox* boxes_unattended_setup_box_new (gboolean live, const gchar* product_key_format, gboolean needs_internet, const gchar* os_name) {
#line 94 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return boxes_unattended_setup_box_construct (BOXES_TYPE_UNATTENDED_SETUP_BOX, live, product_key_format, needs_internet, os_name);
#line 288 "unattended-setup-box.c"
}


static void _boxes_unattended_setup_box_update_express_toggle_g_network_monitor_network_changed (GNetworkMonitor* _sender, gboolean available, gpointer self) {
#line 117 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_update_express_toggle ((BoxesUnattendedSetupBox*) self, available);
#line 295 "unattended-setup-box.c"
}


void boxes_unattended_setup_box_clean_up (BoxesUnattendedSetupBox* self) {
	GNetworkMonitor* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
#line 116 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 117 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = g_network_monitor_get_default ();
#line 117 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_signal_parse_name ("network-changed", g_network_monitor_get_type (), &_tmp1_, NULL, FALSE);
#line 117 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_signal_handlers_disconnect_matched (_tmp0_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _boxes_unattended_setup_box_update_express_toggle_g_network_monitor_network_changed, self);
#line 310 "unattended-setup-box.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 126 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return self ? g_object_ref (self) : NULL;
#line 317 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_setup_express_toggle (BoxesUnattendedSetupBox* self, gboolean live, gboolean needs_internet) {
	GtkSwitch* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GNetworkMonitor* network_monitor = NULL;
	GNetworkMonitor* _tmp3_ = NULL;
	GNetworkMonitor* _tmp4_ = NULL;
	GNetworkMonitor* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	GNetworkMonitor* _tmp7_ = NULL;
#line 120 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 121 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->express_toggle;
#line 121 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = live;
#line 121 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_switch_set_active (_tmp0_, !_tmp1_);
#line 123 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = needs_internet;
#line 123 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (!_tmp2_) {
#line 124 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		return;
#line 345 "unattended-setup-box.c"
	}
#line 126 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp3_ = g_network_monitor_get_default ();
#line 126 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 126 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	network_monitor = _tmp4_;
#line 127 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp5_ = network_monitor;
#line 127 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp6_ = g_network_monitor_get_network_available (_tmp5_);
#line 127 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_update_express_toggle (self, _tmp6_);
#line 128 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp7_ = network_monitor;
#line 128 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_signal_connect_object (_tmp7_, "network-changed", (GCallback) _boxes_unattended_setup_box_update_express_toggle_g_network_monitor_network_changed, self, 0);
#line 120 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (network_monitor);
#line 365 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_update_express_toggle (BoxesUnattendedSetupBox* self, gboolean network_available) {
	gboolean _tmp0_ = FALSE;
#line 131 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 132 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = network_available;
#line 132 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp0_) {
#line 377 "unattended-setup-box.c"
		GtkSwitch* _tmp1_ = NULL;
#line 133 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp1_ = self->priv->express_toggle;
#line 133 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp1_, TRUE);
#line 383 "unattended-setup-box.c"
	} else {
		GtkSwitch* _tmp2_ = NULL;
		GtkSwitch* _tmp3_ = NULL;
#line 135 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp2_ = self->priv->express_toggle;
#line 135 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp2_, FALSE);
#line 136 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp3_ = self->priv->express_toggle;
#line 136 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_switch_set_active (_tmp3_, FALSE);
#line 395 "unattended-setup-box.c"
	}
}


static void boxes_unattended_setup_box_on_mandatory_input_changed (BoxesUnattendedSetupBox* self) {
#line 141 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 142 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_notify ((GObject*) self, "ready-to-create");
#line 405 "unattended-setup-box.c"
}


static void _boxes_unattended_setup_box_on_mandatory_input_changed_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_on_mandatory_input_changed ((BoxesUnattendedSetupBox*) self);
#line 412 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_on_username_entry_activated (BoxesUnattendedSetupBox* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 146 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 147 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = boxes_unattended_setup_box_get_ready_for_express (self);
#line 147 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = _tmp0_;
#line 147 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp1_) {
#line 148 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_signal_emit_by_name (self, "user-wants-to-create");
#line 429 "unattended-setup-box.c"
	} else {
		gboolean _tmp2_ = FALSE;
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
#line 149 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp3_ = boxes_unattended_setup_box_get_username (self);
#line 149 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp4_ = _tmp3_;
#line 149 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		if (g_strcmp0 (_tmp4_, "") != 0) {
#line 440 "unattended-setup-box.c"
			const gchar* _tmp5_ = NULL;
#line 149 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp5_ = self->priv->product_key_format;
#line 149 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp2_ = _tmp5_ != NULL;
#line 446 "unattended-setup-box.c"
		} else {
#line 149 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp2_ = FALSE;
#line 450 "unattended-setup-box.c"
		}
#line 149 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		if (_tmp2_) {
#line 454 "unattended-setup-box.c"
			GtkEntry* _tmp6_ = NULL;
#line 150 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp6_ = self->priv->product_key_entry;
#line 150 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			gtk_widget_grab_focus ((GtkWidget*) _tmp6_);
#line 460 "unattended-setup-box.c"
		}
	}
}


static void _boxes_unattended_setup_box_on_username_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_on_username_entry_activated ((BoxesUnattendedSetupBox*) self);
#line 469 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_on_password_button_clicked (BoxesUnattendedSetupBox* self) {
	GtkNotebook* _tmp0_ = NULL;
	GtkEntry* _tmp1_ = NULL;
#line 154 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 155 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->password_notebook;
#line 155 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_notebook_next_page (_tmp0_);
#line 156 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = self->priv->password_entry;
#line 156 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_grab_focus ((GtkWidget*) _tmp1_);
#line 486 "unattended-setup-box.c"
}


static void _boxes_unattended_setup_box_on_password_button_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_on_password_button_clicked ((BoxesUnattendedSetupBox*) self);
#line 493 "unattended-setup-box.c"
}


static gboolean boxes_unattended_setup_box_on_password_entry_focus_out (BoxesUnattendedSetupBox* self) {
	gboolean result = FALSE;
	GtkEntry* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
#line 160 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 161 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->password_entry;
#line 161 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = gtk_entry_get_text_length (_tmp0_);
#line 161 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = _tmp1_;
#line 161 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp2_ == ((guint) 0)) {
#line 512 "unattended-setup-box.c"
		GtkNotebook* _tmp3_ = NULL;
#line 162 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp3_ = self->priv->password_notebook;
#line 162 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_notebook_prev_page (_tmp3_);
#line 518 "unattended-setup-box.c"
	}
#line 163 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	result = FALSE;
#line 163 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 524 "unattended-setup-box.c"
}


static gboolean _boxes_unattended_setup_box_on_password_entry_focus_out_gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self) {
	gboolean result;
	result = boxes_unattended_setup_box_on_password_entry_focus_out ((BoxesUnattendedSetupBox*) self);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 533 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_on_password_entry_activated (BoxesUnattendedSetupBox* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 167 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 168 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = boxes_unattended_setup_box_get_ready_for_express (self);
#line 168 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = _tmp0_;
#line 168 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp1_) {
#line 169 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_signal_emit_by_name (self, "user-wants-to-create");
#line 550 "unattended-setup-box.c"
	} else {
		const gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
#line 170 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp2_ = boxes_unattended_setup_box_get_username (self);
#line 170 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp3_ = _tmp2_;
#line 170 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		if (g_strcmp0 (_tmp3_, "") == 0) {
#line 560 "unattended-setup-box.c"
			GtkEntry* _tmp4_ = NULL;
#line 171 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp4_ = self->priv->username_entry;
#line 171 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			gtk_widget_grab_focus ((GtkWidget*) _tmp4_);
#line 566 "unattended-setup-box.c"
		} else {
			const gchar* _tmp5_ = NULL;
#line 172 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp5_ = self->priv->product_key_format;
#line 172 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			if (_tmp5_ != NULL) {
#line 573 "unattended-setup-box.c"
				GtkEntry* _tmp6_ = NULL;
#line 173 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp6_ = self->priv->product_key_entry;
#line 173 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				gtk_widget_grab_focus ((GtkWidget*) _tmp6_);
#line 579 "unattended-setup-box.c"
			}
		}
	}
}


static void _boxes_unattended_setup_box_on_password_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_on_password_entry_activated ((BoxesUnattendedSetupBox*) self);
#line 589 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_on_key_entry_activated (BoxesUnattendedSetupBox* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 177 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 178 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = boxes_unattended_setup_box_get_ready_for_express (self);
#line 178 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = _tmp0_;
#line 178 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp1_) {
#line 179 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_signal_emit_by_name (self, "user-wants-to-create");
#line 606 "unattended-setup-box.c"
	} else {
		GtkEntry* _tmp2_ = NULL;
		guint _tmp3_ = 0U;
		guint _tmp4_ = 0U;
		const gchar* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
#line 180 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp2_ = self->priv->product_key_entry;
#line 180 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp3_ = gtk_entry_get_text_length (_tmp2_);
#line 180 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp4_ = _tmp3_;
#line 180 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp5_ = self->priv->product_key_format;
#line 180 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp6_ = strlen (_tmp5_);
#line 180 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp7_ = _tmp6_;
#line 180 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		if (_tmp4_ == ((guint) _tmp7_)) {
#line 628 "unattended-setup-box.c"
			GtkEntry* _tmp8_ = NULL;
#line 181 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp8_ = self->priv->username_entry;
#line 181 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			gtk_widget_grab_focus ((GtkWidget*) _tmp8_);
#line 634 "unattended-setup-box.c"
		}
	}
}


static void _boxes_unattended_setup_box_on_key_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_on_key_entry_activated ((BoxesUnattendedSetupBox*) self);
#line 643 "unattended-setup-box.c"
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
#line 996 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 997 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp0_ = index;
#line 997 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp1_ = ((gchar*) self)[_tmp0_];
#line 997 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	result = _tmp1_;
#line 997 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	return result;
#line 661 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_on_key_text_inserted (BoxesUnattendedSetupBox* self, const gchar* text, gint text_length, gint* position) {
	gboolean _tmp0_ = FALSE;
	gchar* _result_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp40_ = NULL;
	GtkEntry* _tmp48_ = NULL;
#line 187 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 187 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (text != NULL);
#line 188 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->we_inserted_text;
#line 188 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp0_) {
#line 189 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		return;
#line 681 "unattended-setup-box.c"
	}
#line 191 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = g_strdup ("");
#line 191 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_result_ = _tmp1_;
#line 687 "unattended-setup-box.c"
	{
		guint i = 0U;
		guint j = 0U;
		gint _tmp2_ = 0;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		i = (guint) 0;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp2_ = *position;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		j = (guint) _tmp2_;
#line 698 "unattended-setup-box.c"
		{
			gboolean _tmp3_ = FALSE;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp3_ = TRUE;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			while (TRUE) {
#line 705 "unattended-setup-box.c"
				gboolean _tmp4_ = FALSE;
				guint _tmp5_ = 0U;
				gint _tmp6_ = 0;
				gchar character = '\0';
				const gchar* _tmp11_ = NULL;
				guint _tmp12_ = 0U;
				gchar _tmp13_ = '\0';
				gchar allowed_char = '\0';
				const gchar* _tmp14_ = NULL;
				guint _tmp15_ = 0U;
				gchar _tmp16_ = '\0';
				gboolean skip_input_char = FALSE;
				gchar _tmp17_ = '\0';
				guint _tmp32_ = 0U;
				gboolean _tmp33_ = FALSE;
				const gchar* _tmp34_ = NULL;
				gchar _tmp35_ = '\0';
				gchar* _tmp36_ = NULL;
				gchar* _tmp37_ = NULL;
				gchar* _tmp38_ = NULL;
				guint _tmp39_ = 0U;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				if (!_tmp3_) {
#line 729 "unattended-setup-box.c"
				}
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp3_ = FALSE;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp5_ = i;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp6_ = text_length;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				if (_tmp5_ < ((guint) _tmp6_)) {
#line 739 "unattended-setup-box.c"
					guint _tmp7_ = 0U;
					const gchar* _tmp8_ = NULL;
					gint _tmp9_ = 0;
					gint _tmp10_ = 0;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp7_ = j;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp8_ = self->priv->product_key_format;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp9_ = strlen (_tmp8_);
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp10_ = _tmp9_;
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp4_ = _tmp7_ < ((guint) _tmp10_);
#line 754 "unattended-setup-box.c"
				} else {
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp4_ = FALSE;
#line 758 "unattended-setup-box.c"
				}
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				if (!_tmp4_) {
#line 193 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					break;
#line 764 "unattended-setup-box.c"
				}
#line 194 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp11_ = text;
#line 194 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp12_ = i;
#line 194 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp13_ = string_get (_tmp11_, (glong) _tmp12_);
#line 194 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				character = _tmp13_;
#line 195 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp14_ = self->priv->product_key_format;
#line 195 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp15_ = j;
#line 195 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp16_ = string_get (_tmp14_, (glong) _tmp15_);
#line 195 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				allowed_char = _tmp16_;
#line 197 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				skip_input_char = FALSE;
#line 198 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp17_ = allowed_char;
#line 198 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				switch (_tmp17_) {
#line 198 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					case '@':
#line 790 "unattended-setup-box.c"
					{
#line 200 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						break;
#line 794 "unattended-setup-box.c"
					}
#line 198 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					case '%':
#line 798 "unattended-setup-box.c"
					{
						gchar _tmp18_ = '\0';
						gboolean _tmp19_ = FALSE;
#line 203 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp18_ = character;
#line 203 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp19_ = g_ascii_isalpha (_tmp18_);
#line 203 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						if (!_tmp19_) {
#line 204 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							skip_input_char = TRUE;
#line 810 "unattended-setup-box.c"
						}
#line 205 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						break;
#line 814 "unattended-setup-box.c"
					}
#line 198 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					case '#':
#line 818 "unattended-setup-box.c"
					{
						gchar _tmp20_ = '\0';
						gboolean _tmp21_ = FALSE;
#line 208 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp20_ = character;
#line 208 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp21_ = g_ascii_isdigit (_tmp20_);
#line 208 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						if (!_tmp21_) {
#line 209 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							skip_input_char = TRUE;
#line 830 "unattended-setup-box.c"
						}
#line 210 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						break;
#line 834 "unattended-setup-box.c"
					}
#line 198 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					case '$':
#line 838 "unattended-setup-box.c"
					{
						gchar _tmp22_ = '\0';
						gboolean _tmp23_ = FALSE;
#line 213 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp22_ = character;
#line 213 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp23_ = g_ascii_isalnum (_tmp22_);
#line 213 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						if (!_tmp23_) {
#line 214 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							skip_input_char = TRUE;
#line 850 "unattended-setup-box.c"
						}
#line 215 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						break;
#line 854 "unattended-setup-box.c"
					}
					default:
					{
						gchar _tmp24_ = '\0';
						gchar _tmp25_ = '\0';
#line 218 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp24_ = character;
#line 218 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp25_ = allowed_char;
#line 218 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						if (_tmp24_ != _tmp25_) {
#line 866 "unattended-setup-box.c"
							const gchar* _tmp26_ = NULL;
							gchar _tmp27_ = '\0';
							gchar* _tmp28_ = NULL;
							gchar* _tmp29_ = NULL;
							gchar* _tmp30_ = NULL;
							guint _tmp31_ = 0U;
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_tmp26_ = _result_;
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_tmp27_ = allowed_char;
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_tmp28_ = g_strdup_printf ("%c", _tmp27_);
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_tmp29_ = _tmp28_;
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_tmp30_ = g_strconcat (_tmp26_, _tmp29_, NULL);
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_g_free0 (_result_);
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_result_ = _tmp30_;
#line 219 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_g_free0 (_tmp29_);
#line 220 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							_tmp31_ = j;
#line 220 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							j = _tmp31_ + 1;
#line 222 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
							continue;
#line 895 "unattended-setup-box.c"
						}
#line 225 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						break;
#line 899 "unattended-setup-box.c"
					}
				}
#line 228 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp32_ = i;
#line 228 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				i = _tmp32_ + 1;
#line 229 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp33_ = skip_input_char;
#line 229 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				if (_tmp33_) {
#line 230 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					continue;
#line 912 "unattended-setup-box.c"
				}
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp34_ = _result_;
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp35_ = character;
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp36_ = g_strdup_printf ("%c", _tmp35_);
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp37_ = _tmp36_;
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp38_ = g_strconcat (_tmp34_, _tmp37_, NULL);
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_g_free0 (_result_);
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_result_ = _tmp38_;
#line 232 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_g_free0 (_tmp37_);
#line 233 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp39_ = j;
#line 233 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				j = _tmp39_ + 1;
#line 934 "unattended-setup-box.c"
			}
		}
	}
#line 236 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp40_ = _result_;
#line 236 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (g_strcmp0 (_tmp40_, "") != 0) {
#line 942 "unattended-setup-box.c"
		GtkEntry* _tmp41_ = NULL;
		const gchar* _tmp42_ = NULL;
		gchar* _tmp43_ = NULL;
		gchar* _tmp44_ = NULL;
		const gchar* _tmp45_ = NULL;
		gint _tmp46_ = 0;
		gint _tmp47_ = 0;
#line 237 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		self->priv->we_inserted_text = TRUE;
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp41_ = self->priv->product_key_entry;
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp42_ = _result_;
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp43_ = g_utf8_strup (_tmp42_, (gssize) (-1));
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp44_ = _tmp43_;
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp45_ = _result_;
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp46_ = strlen (_tmp45_);
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp47_ = _tmp46_;
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		gtk_editable_insert_text ((GtkEditable*) _tmp41_, _tmp44_, _tmp47_, position);
#line 238 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_g_free0 (_tmp44_);
#line 239 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		self->priv->we_inserted_text = FALSE;
#line 972 "unattended-setup-box.c"
	}
#line 242 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp48_ = self->priv->product_key_entry;
#line 242 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_signal_stop_emission_by_name (_tmp48_, "insert-text");
#line 187 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_free0 (_result_);
#line 980 "unattended-setup-box.c"
}


static void _boxes_unattended_setup_box_on_key_text_inserted_gtk_editable_insert_text (GtkEditable* _sender, const gchar* new_text, gint new_text_length, gint* position, gpointer self) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_on_key_text_inserted ((BoxesUnattendedSetupBox*) self, new_text, new_text_length, position);
#line 987 "unattended-setup-box.c"
}


gboolean boxes_unattended_setup_box_get_ready_for_express (BoxesUnattendedSetupBox* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 6 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 7 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = boxes_unattended_setup_box_get_username (self);
#line 7 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = _tmp1_;
#line 7 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (g_strcmp0 (_tmp2_, "") != 0) {
#line 1004 "unattended-setup-box.c"
		gboolean _tmp3_ = FALSE;
		const gchar* _tmp4_ = NULL;
#line 8 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp4_ = self->priv->product_key_format;
#line 8 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		if (_tmp4_ == NULL) {
#line 8 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp3_ = TRUE;
#line 1013 "unattended-setup-box.c"
		} else {
			GtkEntry* _tmp5_ = NULL;
			guint _tmp6_ = 0U;
			guint _tmp7_ = 0U;
			const gchar* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gint _tmp10_ = 0;
#line 9 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp5_ = self->priv->product_key_entry;
#line 9 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp6_ = gtk_entry_get_text_length (_tmp5_);
#line 9 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp7_ = _tmp6_;
#line 9 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp8_ = self->priv->product_key_format;
#line 9 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp9_ = strlen (_tmp8_);
#line 9 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp10_ = _tmp9_;
#line 9 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			_tmp3_ = _tmp7_ == ((guint) _tmp10_);
#line 1035 "unattended-setup-box.c"
		}
#line 8 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp0_ = _tmp3_;
#line 1039 "unattended-setup-box.c"
	} else {
#line 7 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp0_ = FALSE;
#line 1043 "unattended-setup-box.c"
	}
#line 7 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	result = _tmp0_;
#line 7 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 1049 "unattended-setup-box.c"
}


gboolean boxes_unattended_setup_box_get_ready_to_create (BoxesUnattendedSetupBox* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	GtkSwitch* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
#line 14 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = self->priv->express_toggle;
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = gtk_switch_get_active (_tmp1_);
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp3_ = _tmp2_;
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (!_tmp3_) {
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp0_ = TRUE;
#line 1071 "unattended-setup-box.c"
	} else {
		gboolean _tmp4_ = FALSE;
		gboolean _tmp5_ = FALSE;
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp4_ = boxes_unattended_setup_box_get_ready_for_express (self);
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp5_ = _tmp4_;
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp0_ = _tmp5_;
#line 1081 "unattended-setup-box.c"
	}
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	result = _tmp0_;
#line 15 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 1087 "unattended-setup-box.c"
}


gboolean boxes_unattended_setup_box_get_express_install (BoxesUnattendedSetupBox* self) {
	gboolean result;
	GtkSwitch* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 20 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 21 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->express_toggle;
#line 21 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = gtk_switch_get_active (_tmp0_);
#line 21 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = _tmp1_;
#line 21 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	result = _tmp2_;
#line 21 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 1108 "unattended-setup-box.c"
}


void boxes_unattended_setup_box_set_express_install (BoxesUnattendedSetupBox* self, gboolean value) {
	GtkSwitch* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 24 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 25 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->express_toggle;
#line 25 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = value;
#line 25 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_switch_set_active (_tmp0_, _tmp1_);
#line 24 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_notify ((GObject *) self, "express-install");
#line 1125 "unattended-setup-box.c"
}


const gchar* boxes_unattended_setup_box_get_username (BoxesUnattendedSetupBox* self) {
	const gchar* result;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 30 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 30 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->username_entry;
#line 30 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 30 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = _tmp1_;
#line 30 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	result = _tmp2_;
#line 30 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 1146 "unattended-setup-box.c"
}


gchar* boxes_unattended_setup_box_get_password (BoxesUnattendedSetupBox* self) {
	gchar* result;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 34 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 34 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->password_entry;
#line 34 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 34 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = _tmp1_;
#line 34 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 34 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	result = _tmp3_;
#line 34 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 1170 "unattended-setup-box.c"
}


static gchar* g_unichar_to_string (gunichar self) {
	gchar* result = NULL;
	gchar* str = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 857 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp0_ = g_new0 (gchar, 7);
#line 857 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	str = (gchar*) _tmp0_;
#line 858 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp1_ = str;
#line 858 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_unichar_to_utf8 (self, _tmp1_);
#line 859 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	result = str;
#line 859 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	return result;
#line 1191 "unattended-setup-box.c"
}


gchar* boxes_unattended_setup_box_get_hidden_password (BoxesUnattendedSetupBox* self) {
	gchar* result;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
#line 38 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 39 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp0_ = self->priv->password_entry;
#line 39 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 39 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp2_ = _tmp1_;
#line 39 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp3_ = strlen (_tmp2_);
#line 39 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp4_ = _tmp3_;
#line 39 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp4_ > 0) {
#line 1216 "unattended-setup-box.c"
		gchar* str = NULL;
		gchar* _tmp5_ = NULL;
#line 40 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp5_ = g_strdup ("");
#line 40 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		str = _tmp5_;
#line 1223 "unattended-setup-box.c"
		{
			gint i = 0;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
			i = 0;
#line 1228 "unattended-setup-box.c"
			{
				gboolean _tmp6_ = FALSE;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				_tmp6_ = TRUE;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
				while (TRUE) {
#line 1235 "unattended-setup-box.c"
					gint _tmp8_ = 0;
					GtkEntry* _tmp9_ = NULL;
					guint _tmp10_ = 0U;
					guint _tmp11_ = 0U;
					const gchar* _tmp12_ = NULL;
					GtkEntry* _tmp13_ = NULL;
					gunichar _tmp14_ = 0U;
					gchar* _tmp15_ = NULL;
					gchar* _tmp16_ = NULL;
					gchar* _tmp17_ = NULL;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					if (!_tmp6_) {
#line 1248 "unattended-setup-box.c"
						gint _tmp7_ = 0;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						_tmp7_ = i;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						i = _tmp7_ + 1;
#line 1254 "unattended-setup-box.c"
					}
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp6_ = FALSE;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp8_ = i;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp9_ = self->priv->password_entry;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp10_ = gtk_entry_get_text_length (_tmp9_);
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp11_ = _tmp10_;
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					if (!(((guint) _tmp8_) < _tmp11_)) {
#line 41 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
						break;
#line 1270 "unattended-setup-box.c"
					}
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp12_ = str;
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp13_ = self->priv->password_entry;
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp14_ = gtk_entry_get_invisible_char (_tmp13_);
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp15_ = g_unichar_to_string (_tmp14_);
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp16_ = _tmp15_;
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_tmp17_ = g_strconcat (_tmp12_, _tmp16_, NULL);
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_g_free0 (str);
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					str = _tmp17_;
#line 42 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
					_g_free0 (_tmp16_);
#line 1290 "unattended-setup-box.c"
				}
			}
		}
#line 44 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		result = str;
#line 44 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		return result;
#line 1298 "unattended-setup-box.c"
	} else {
		const gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
#line 46 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp18_ = _ ("no password");
#line 46 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp19_ = g_strdup (_tmp18_);
#line 46 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		result = _tmp19_;
#line 46 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		return result;
#line 1310 "unattended-setup-box.c"
	}
}


gchar* boxes_unattended_setup_box_get_product_key (BoxesUnattendedSetupBox* self) {
	gchar* result;
	const gchar* _tmp0_ = NULL;
	GtkEntry* _tmp1_ = NULL;
	gchar* _tmp5_ = NULL;
#line 51 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp1_ = self->priv->product_key_entry;
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (_tmp1_ != NULL) {
#line 1326 "unattended-setup-box.c"
		GtkEntry* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp2_ = self->priv->product_key_entry;
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp3_ = gtk_entry_get_text (_tmp2_);
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp4_ = _tmp3_;
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp0_ = _tmp4_;
#line 1338 "unattended-setup-box.c"
	} else {
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp0_ = NULL;
#line 1342 "unattended-setup-box.c"
	}
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_tmp5_ = g_strdup (_tmp0_);
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	result = _tmp5_;
#line 52 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	return result;
#line 1350 "unattended-setup-box.c"
}


void boxes_unattended_setup_box_set_avatar_path (BoxesUnattendedSetupBox* self, const gchar* value) {
	GError * _inner_error_ = NULL;
#line 57 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_return_if_fail (self != NULL);
#line 1358 "unattended-setup-box.c"
	{
		GdkPixbuf* pixbuf = NULL;
		const gchar* _tmp0_ = NULL;
		GdkPixbuf* _tmp1_ = NULL;
		GtkImage* _tmp2_ = NULL;
#line 59 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp0_ = value;
#line 59 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp1_ = gdk_pixbuf_new_from_file_at_scale (_tmp0_, 64, 64, TRUE, &_inner_error_);
#line 59 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		pixbuf = _tmp1_;
#line 59 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1372 "unattended-setup-box.c"
			goto __catch85_g_error;
		}
#line 60 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp2_ = self->priv->user_avatar;
#line 60 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_object_set (_tmp2_, "pixbuf", pixbuf, NULL);
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_g_object_unref0 (pixbuf);
#line 1381 "unattended-setup-box.c"
	}
	goto __finally85;
	__catch85_g_error:
	{
		GError* _error_ = NULL;
		const gchar* _tmp3_ = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_error_ = _inner_error_;
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_inner_error_ = NULL;
#line 62 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp3_ = value;
#line 62 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp4_ = _error_;
#line 62 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_tmp5_ = _tmp4_->message;
#line 62 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_debug ("unattended-setup-box.vala:62: Failed to load user avatar file '%s': %s", _tmp3_, _tmp5_);
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		_g_error_free0 (_error_);
#line 1404 "unattended-setup-box.c"
	}
	__finally85:
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_clear_error (&_inner_error_);
#line 58 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		return;
#line 1415 "unattended-setup-box.c"
	}
#line 57 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_notify ((GObject *) self, "avatar-path");
#line 1419 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_class_init (BoxesUnattendedSetupBoxClass * klass) {
	gint BoxesUnattendedSetupBox_private_offset;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	boxes_unattended_setup_box_parent_class = g_type_class_peek_parent (klass);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_type_class_add_private (klass, sizeof (BoxesUnattendedSetupBoxPrivate));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_boxes_unattended_setup_box_get_property;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_boxes_unattended_setup_box_set_property;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	G_OBJECT_CLASS (klass)->finalize = boxes_unattended_setup_box_finalize;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_READY_FOR_EXPRESS, g_param_spec_boolean ("ready-for-express", "ready-for-express", "ready-for-express", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_READY_TO_CREATE, g_param_spec_boolean ("ready-to-create", "ready-to-create", "ready-to-create", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_EXPRESS_INSTALL, g_param_spec_boolean ("express-install", "express-install", "express-install", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_USERNAME, g_param_spec_string ("username", "username", "username", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_PASSWORD, g_param_spec_string ("password", "password", "password", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_HIDDEN_PASSWORD, g_param_spec_string ("hidden-password", "hidden-password", "hidden-password", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_PRODUCT_KEY, g_param_spec_string ("product-key", "product-key", "product-key", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOXES_UNATTENDED_SETUP_BOX_AVATAR_PATH, g_param_spec_string ("avatar-path", "avatar-path", "avatar-path", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	BoxesUnattendedSetupBox_private_offset = g_type_class_get_instance_private_offset (klass);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/gnome/Boxes/ui/unattended-setup-box.ui");
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	g_signal_new ("user_wants_to_create", BOXES_TYPE_UNATTENDED_SETUP_BOX, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "needs_internet_bar", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, needs_internet_bar));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "needs_internet_label", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, needs_internet_label));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "setup_grid", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, setup_grid));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "express_label", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, express_label));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "express_toggle", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, express_toggle));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "user_avatar", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, user_avatar));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "username_entry", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, username_entry));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "password_notebook", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, password_notebook));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "password_entry", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, password_entry));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "product_key_label", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, product_key_label));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "product_key_entry", FALSE, BoxesUnattendedSetupBox_private_offset + G_STRUCT_OFFSET (BoxesUnattendedSetupBoxPrivate, product_key_entry));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_mandatory_input_changed", G_CALLBACK(_boxes_unattended_setup_box_on_mandatory_input_changed_g_object_notify));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_username_entry_activated", G_CALLBACK(_boxes_unattended_setup_box_on_username_entry_activated_gtk_entry_activate));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_password_button_clicked", G_CALLBACK(_boxes_unattended_setup_box_on_password_button_clicked_gtk_button_clicked));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_password_entry_focus_out", G_CALLBACK(_boxes_unattended_setup_box_on_password_entry_focus_out_gtk_widget_focus_out_event));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_password_entry_activated", G_CALLBACK(_boxes_unattended_setup_box_on_password_entry_activated_gtk_entry_activate));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_key_entry_activated", G_CALLBACK(_boxes_unattended_setup_box_on_key_entry_activated_gtk_entry_activate));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_key_text_inserted", G_CALLBACK(_boxes_unattended_setup_box_on_key_text_inserted_gtk_editable_insert_text));
#line 1493 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_instance_init (BoxesUnattendedSetupBox * self) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	self->priv = BOXES_UNATTENDED_SETUP_BOX_GET_PRIVATE (self);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 1502 "unattended-setup-box.c"
}


static void boxes_unattended_setup_box_finalize (GObject* obj) {
	BoxesUnattendedSetupBox * self;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOXES_TYPE_UNATTENDED_SETUP_BOX, BoxesUnattendedSetupBox);
#line 70 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->needs_internet_bar);
#line 72 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->needs_internet_label);
#line 74 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->setup_grid);
#line 76 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->express_label);
#line 78 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->express_toggle);
#line 80 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->user_avatar);
#line 82 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->username_entry);
#line 84 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->password_notebook);
#line 86 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->password_entry);
#line 88 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->product_key_label);
#line 90 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_object_unref0 (self->priv->product_key_entry);
#line 92 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	_g_free0 (self->priv->product_key_format);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	G_OBJECT_CLASS (boxes_unattended_setup_box_parent_class)->finalize (obj);
#line 1536 "unattended-setup-box.c"
}


GType boxes_unattended_setup_box_get_type (void) {
	static volatile gsize boxes_unattended_setup_box_type_id__volatile = 0;
	if (g_once_init_enter (&boxes_unattended_setup_box_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoxesUnattendedSetupBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) boxes_unattended_setup_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoxesUnattendedSetupBox), 0, (GInstanceInitFunc) boxes_unattended_setup_box_instance_init, NULL };
		GType boxes_unattended_setup_box_type_id;
		boxes_unattended_setup_box_type_id = g_type_register_static (gtk_box_get_type (), "BoxesUnattendedSetupBox", &g_define_type_info, 0);
		g_once_init_leave (&boxes_unattended_setup_box_type_id__volatile, boxes_unattended_setup_box_type_id);
	}
	return boxes_unattended_setup_box_type_id__volatile;
}


static void _vala_boxes_unattended_setup_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	BoxesUnattendedSetupBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BOXES_TYPE_UNATTENDED_SETUP_BOX, BoxesUnattendedSetupBox);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	switch (property_id) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_READY_FOR_EXPRESS:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_value_set_boolean (value, boxes_unattended_setup_box_get_ready_for_express (self));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_READY_TO_CREATE:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_value_set_boolean (value, boxes_unattended_setup_box_get_ready_to_create (self));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_EXPRESS_INSTALL:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_value_set_boolean (value, boxes_unattended_setup_box_get_express_install (self));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_USERNAME:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_value_set_string (value, boxes_unattended_setup_box_get_username (self));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_PASSWORD:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_value_take_string (value, boxes_unattended_setup_box_get_password (self));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_HIDDEN_PASSWORD:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_value_take_string (value, boxes_unattended_setup_box_get_hidden_password (self));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_PRODUCT_KEY:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		g_value_take_string (value, boxes_unattended_setup_box_get_product_key (self));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 1599 "unattended-setup-box.c"
		default:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 1605 "unattended-setup-box.c"
	}
}


static void _vala_boxes_unattended_setup_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	BoxesUnattendedSetupBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BOXES_TYPE_UNATTENDED_SETUP_BOX, BoxesUnattendedSetupBox);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
	switch (property_id) {
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_EXPRESS_INSTALL:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		boxes_unattended_setup_box_set_express_install (self, g_value_get_boolean (value));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		case BOXES_UNATTENDED_SETUP_BOX_AVATAR_PATH:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		boxes_unattended_setup_box_set_avatar_path (self, g_value_get_string (value));
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 1627 "unattended-setup-box.c"
		default:
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 4 "/home/zeenix/checkout/gnome/gnome-boxes/src/unattended-setup-box.vala"
		break;
#line 1633 "unattended-setup-box.c"
	}
}



